databaseChangeLog:
  - preConditions:
      - dbms:
          type: mysql
  - changeSet:
      id: mysql_schema_init
      author: root_db_initializer
      comment: 
      changes:
        - sql:
            sql: GRANT ALL PRIVILEGES ON *.* TO 'liquibase' WITH GRANT OPTION;
        - sql:
            sql: GRANT RELOAD ON *.* TO 'liquibase';
