# This is a basic workflow to help you get started with Actions

name: rp5-k8s-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Load 1Password secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          LIQUIBASE_COMMAND_USERNAME: op://statsaga-test/ngsklgnnwyd5x4xqjvblqxzuga/username
          LIQUIBASE_COMMAND_PASSWORD: op://statsaga-test/ngsklgnnwyd5x4xqjvblqxzuga/password
          

      # Runs a single command using the runners shell
      - name: CD into deploy/test-k3s-mysql
        run: cd deploy/test-k3s-mysql

      - name: Liquibase update
        run: liquibase update
